# Generated by Django 5.2.7 on 2025-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyvalue',
            options={},
        ),
        migrations.RemoveField(
            model_name='keyvalue',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
